### ISSUE TITLE
Adding  Contact Us page

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [Ankit-Saha08/AIFF_Live_Updates#10]
Hi @Ankit-Saha08 can I work for creating a login page for the website?

**Comment by Ankit-Saha08** [comment]
Well @ARCHITABHATTAD, how do you think adding this feature will enhance the concept of the project? Since it is a simple front-end project which doesn't implement any user specific agenda, so how do you think a Login page would improve it?

**Comment by Ankit-Saha08** [comment]
Instead I can recommend you to create a **Contact Us** Page that will be of a form type which consists three input boxes - 
 1. Name
 2. Email ID
 3. Enter Query

@ARCHITABHATTAD  if you can contribute something like this, please let me know, I shall assign you this task!

**Comment by ARCHITABHATTAD** [comment]
@Ankit-Saha08 I can surely create a Contact Us page if that seems more useful

**Comment by Ankit-Saha08** [comment]
@ARCHITABHATTAD Go ahead with it. Please follow the parameters as I stated. 

**Please make a note that you do not change the Base Color / Font of the page. Please Stick to Color coding and font-styles already in use.**

**Comment by Kedarnath-Rothe** [comment]
Please assign this task to me under hactoberfest label

**Comment by ARCHITABHATTAD** [comment]
https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/87604491/b1cf7d09-e852-49d3-a936-62956c47a395

@Ankit-Saha08  I have made the required changes according to the specification. Please let me know if any changes are required.

**Comment by ARCHITABHATTAD** [comment]
@Ankit-Saha08 should I make a PR?

**Comment by Ankit-Saha08** [comment]
@ARCHITABHATTAD please go ahead

**Comment by Ankit-Saha08** [comment]
@ARCHITABHATTAD please create a PR and go ahead with the changes. Also can you please make the color of those input box white?

**Comment by Ankit-Saha08** [comment]
@Kedarnath-Rothe Could please raise a separate Issue and state what changes are you proposing?

**Comment by VivekGuruduttK28** [comment]
Hi @Ankit-Saha08 
I would like to contribute to the website by adding the contact us page.
Can it be assigned to me?

**Comment by Ankit-Saha08** [comment]
Hii @ARCHITABHATTAD. I am sorry to let you know, I had reverted your previous changes. The reason being, the changes which you made did not correspond to latest changes present in the website. I request you to do one thing - Can you please create a separate page for the contact us and upload that? I will then link the new "contactus.html" file that you will upload via the contact us button in the navbar!!

**Comment by Ankit-Saha08** [comment]
I would like you to create a new PR and contribute a separate "ContactUs.html" page.

**Comment by Vanesh37** [comment]
hi @Ankit-Saha08  please assign this issue to me

**Comment by Ankit-Saha08** [comment]
@Vanesh37 Please go ahead. First read my earlier to message in this conversation so that you get an idea of the task. Also make sure to put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

**Comment by Vanesh37** [comment]
@Ankit-Saha08  Ok , I will go through the instructions mentioned  earlier .

**Comment by Vanesh37** [comment]
Hi @Ankit-Saha08  , is this page ok or need to modify

https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/110464597/038555f7-ed37-41b6-a731-1ca4e03026c4
