### ISSUE TITLE
Add a basic Navbar

### ISSUE THREAD

**Issue by Ankit-Saha08** [Ankit-Saha08/AIFF_Live_Updates#13]
### **Aim:**
- To add a basic navbar below the video banner
- Navbar, as of now, should contain to features
   i. Home (index.html)
   ii. Contact Us (page to be created & resolved in issue #10 )

**Additional Note:**
   The navbar element color and font-styling to correspond to that of the existing page.

**Comment by TandinDev** [comment]
I can work on this. Can you please assign this to me.

**Comment by Ankit-Saha08** [comment]
Certainly go ahead with it.

**Comment by TandinDev** [comment]
Thank you so much.

**Comment by TandinDev** [comment]
Hello @Ankit-Saha08, I have created the PR: https://github.com/Ankit-Saha08/AIFF_Live_Updates/pull/15/files

**Comment by Ankit-Saha08** [comment]
Thanks @TandinDev for your contribution

**Comment by TandinDev** [comment]
Thank you for the oppurtunity. Please let me know if there are more, I can contribute. :)

**Comment by Ankit-Saha08** [comment]
Well if you can, you may enhance this contribution a bit more infact.
Can you adjust the navbar's position just below the video banner at head of the page?

**Comment by TandinDev** [comment]
Sure I can. Do you want a new banner under this
![Screenshot from 2023-10-07 19-46-28](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/62091702/240ff02b-e13e-4620-b5a1-0941695359fe)

or bring the previous banner to this new position?

**Comment by Ankit-Saha08** [comment]
Bring the previous navbar which you already contributed under this video-banner. The positioning should be between this banner and the first paragraph.

**Comment by TandinDev** [comment]
Sure, on it.

**Comment by TandinDev** [comment]
Hello @Ankit-Saha08 , I have created the PR and I have also attached an image to the PR.

https://github.com/Ankit-Saha08/AIFF_Live_Updates/pull/16

**Comment by Ankit-Saha08** [comment]
Thanks for your overall contributions. Happy Hacking!!💯:)

**Comment by TandinDev** [comment]
Thank you. :)
