### ISSUE TITLE
Add a footer 

### ISSUE THREAD

**Issue by pragnyapradhan-dev** [Ankit-Saha08/AIFF_Live_Updates#19]
I'd love to make a footer for this webpage. Can you **guide** me a little ?

**Comment by Ankit-Saha08** [comment]
@pragnyapradhan-dev Certainly I'd love to hear more from you on this. Yes you can add a footer. But what will be the content or quick links that you propose to add??

**Comment by pragnyapradhan-dev** [comment]
![image](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/74053800/3fc7809f-0992-4d0f-9b42-5b6c2efa06ca)
Since the website doesn't have much to offer. We can go for something simple like this.  What do you think ?

**Comment by Ankit-Saha08** [comment]
Yeah, it's great to have this. But please substitute that FIFA logo in left top corner with AIFF written there!!
And you can add some quicklinks to youtube channels of - Indian Football and Indian Super League.

**Comment by Ankit-Saha08** [comment]
@pragnyapradhan-dev Please go ahead with the work and make sure to put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

**Comment by pragnyapradhan-dev** [comment]
![image](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/74053800/54e4d789-e9a2-46c2-8e61-53db0526470a)
Is this alright? 
Regarding the links, I'm not sure if it'd look very good if we only add a few YouTube links. I say we just keep it simple for now.
I was also wondering what exactly is the idea behind this webpage. Do you want it to act as an info hub and direct the traffic to the relevant official websites and their socials?

**Comment by Ankit-Saha08** [comment]
Well, the structure and design you made is fine!! But yes I would like you to add the youtube channel links as I mentioned. Well, the base idea is to build this as a promotional website as of now that brings all Indian Football fans at one central where they can find every necessary links to official social and news handles. Like I found once that Indian Football updates are hell lot scattered. So as of now I'm trying to assimilate that in one single place!!

**Comment by Ankit-Saha08** [comment]
@pragnyapradhan-dev you can do one thing. Instead of adding Youtube channel links, do add - icons of Indian Football Facebook, Instagram, X, and Youtube channel's quicklinks. Make sure you put simple icons of those handles and clicking on which will redirect users to the social handles!!
