### ISSUE TITLE
Orientation issue in Mobile View 

### ISSUE THREAD

**Issue by Ankit-Saha08** [Ankit-Saha08/AIFF_Live_Updates#2]
Can anybody adjust the orientation that will be fit for mobile view

**Comment by d-a-ve** [comment]
Is this for the video element? @Ankit-Saha08

**Comment by Ankit-Saha08** [comment]
@d-a-ve No, not for the video element but the orientation of the league logos is changing. So, is it possible to make any adjustments? 

P.S. - For better clarification, I recommend you to visit the site on your mobile - https://ankit-saha08.github.io/AIFF_Live_Updates/

**Comment by annesnour03** [comment]
If you're talking about the big space on mobile, I'll pick this up.
![image](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/76728727/04bb9518-3ee4-4db0-a3cb-6344965a2806)

**Comment by Ankit-Saha08** [comment]
@annesnour03 Yes, I am exactly talking about this issue. Please create a PR from my repo - https://github.com/Ankit-Saha08/AIFF_Live_Updates. I would be glad to merge your contri & get it fixed.

**Comment by Ankit-Saha08** [comment]
@annesnour03 Also make a note that the desktop orientation remains unaltered

**Comment by annesnour03** [comment]
@Ankit-Saha08 should be fixed in #3, mind checking?

**Comment by d-a-ve** [comment]
It seems @annesnour03 has done the issue.

It was the video that was causing that space btw @Ankit-Saha08, that's why I asked initially if it was the video.

**Comment by XNOR8** [comment]
> Can anybody adjust the orientation that will be fit for mobile view

Hey I have tried to make this website mobile responsive but I don't know how to send you the revised files.

**Comment by Ankit-Saha08** [comment]
@d-a-ve Yeah true. Thanks for your interest. However, if you have any further suggestions to make any upgradation, I am open to accept more fixes. Please raise issues if you find any!!

**Comment by Ankit-Saha08** [comment]
@XNOR8 Thanks for your interest. But this issue has been recently been resolved. But I do encourage to raise further issues and also suggest fixes for the same. 
And to contribute or upload your changes please create a PR at first, then commit your changes there. We can further proceed the conversation there itself.
