### ISSUE TITLE
Text inside card not properly aligned

### ISSUE THREAD

**Issue by vinay-s36** [Ankit-Saha08/AIFF_Live_Updates#23]
The text inside the card in not aligned properly, it looks good when all the text are left aligned

![image](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/124019116/f450a20d-6de8-4988-a545-9384ad375292)

**Comment by VivekGuruduttK28** [comment]
Hi @Ankit-Saha08 
I would like to contribute to this issue.
Can it be assigned to me?

**Comment by Ankit-Saha08** [comment]
@vinay-s36 Please go ahead. Also make sure to put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

**Comment by Ankit-Saha08** [comment]
@VivekGuruduttK28 I request you to kindly propose some other enhancement!! :)
