### ISSUE TITLE
Updating the Go to IWL homepage Link

### ISSUE THREAD

**Issue by VivekGuruduttK28** [Ankit-Saha08/AIFF_Live_Updates#24]
Hi @Ankit-Saha08 
On pressing the "Go to IWL homepage" button it is redirected to a wikipedia page.

![image](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/127002789/b980182f-cd63-460b-b2a2-3e577f038d71)

It has to be updated with the proper link. I would like to contribute to this issue.
Can it be assigned to me

**Comment by Ankit-Saha08** [comment]
@VivekGuruduttK28 Please go ahead.

**Comment by VivekGuruduttK28** [comment]
Thank you for assigning this to me @Ankit-Saha08.
Starting to work on the issue.
