### ISSUE TITLE
Carousel addition

### ISSUE THREAD

**Issue by YashaKirad** [Ankit-Saha08/AIFF_Live_Updates#25]
Hello,
Can I add a carousel instead of the rotating football stadium images for #hacktoberfest and align its margin and padding properly?

**Comment by Ankit-Saha08** [comment]
Well, can you suggest some other issue?

**Comment by YashaKirad** [comment]
Sure, can I make the entire website responsive to all devices?
If needed you could also assign me a topic that currently requires help

**Comment by Ankit-Saha08** [comment]
@YashaKirad Please go ahead. Also make sure to put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

**Comment by AvishiJ** [comment]
Hey, can I make carousel design addition in the kits format displayed in the website ?

**Comment by YashaKirad** [comment]
> @YashaKirad Please go ahead. Also make sure to put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

Yep, will do. Thanks!

**Comment by Ankit-Saha08** [comment]
> carousel design

@AvishiJ Please go ahead with the changes and do make sure that you put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

**Comment by AvishiJ** [comment]
@Ankit-Saha08 I have made a PR with snaps attached ,please verify it.

**Comment by YashaKirad** [comment]
Hello, I have made the entire website responsive across all devices. attached snaps below.
Please accept my pull request.

**Comment by YashaKirad** [comment]
![Screenshot (237)](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/92590913/8a4113c2-6997-4e3d-b82d-6448c97ebada)
![Screenshot (239)](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/92590913/942cad90-df05-4784-9155-711cd2c6a5b2)
![Screenshot (238)](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/92590913/894bfc55-2781-422b-89e9-c8530f16ec17)
