### ISSUE TITLE
Addition of a button to scroll to top

### ISSUE THREAD

**Issue by VivekGuruduttK28** [Ankit-Saha08/AIFF_Live_Updates#29]
Hi @Ankit-Saha08,
I noticed that there is no button for scrolling to top of the webpage when the user scrolls down. Addition of this button can help in improving user experience. 
I would like to work on this issue. Can it be assigned to me?

**Comment by Ankit-Saha08** [comment]
@VivekGuruduttK28 yeah it will be a great addition indeed!! Please go ahead. Also make sure to put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

**Comment by VivekGuruduttK28** [comment]
Thank you for assigning this issue to me @Ankit-Saha08.
Starting to work on it. Happy to contribute

**Comment by Ankit-Saha08** [comment]
Thanks for your contribution!!!
