### ISSUE TITLE
Favicon Update Required

### ISSUE THREAD

**Issue by tmsagarofficial** [Ankit-Saha08/AIFF_Live_Updates#30]
I see that currently the site does not have any favicon. I would like to help put up a favicon to suit this project and represent the domain of this project.

Pls assign this issue to me so that i can start working on this. @Ankit-Saha08

**Comment by Ankit-Saha08** [comment]
@tmsagarofficial Please go ahead with the favicon setup as of now!! Also make sure to put a snapshot of the changes you made in your PR conversation area so that i can review before merging.

**Comment by Ankit-Saha08** [comment]
Thanks for your contribution @tmsagarofficial !!
