### ISSUE TITLE
Footer CSS updation

### ISSUE THREAD

**Issue by Ankit-Saha08** [Ankit-Saha08/AIFF_Live_Updates#39]
The design of the footer need to be modified!!

**Comment by vinay-s36** [comment]
Hii @Ankit-Saha08 I would like to help on this issue

**Comment by enayush** [comment]
Hi @Ankit-Saha08,
I would like to work on this issue

**Comment by 08Uzair** [comment]
Please Assign this to me

**Comment by Ankit-Saha08** [comment]
@08Uzair Sorry this issue is resolved. You can suggest something else!!
