### ISSUE TITLE
Footer social media links opening on the same tab as the current tab

### ISSUE THREAD

**Issue by vinay-s36** [Ankit-Saha08/AIFF_Live_Updates#47]
I would like to point it out that social media links in the footer of the website are opening in the same tab as of the current tab.
This will hinder the user Experience . And hence should be made such that links open in a separate tab.

![image](https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/124019116/cae11b52-1e5c-4df6-bb45-d7c7651d42bd)

**Comment by Ankit-Saha08** [comment]
Yeah, that's fine. No improvement required for this. Please look out for something else that can be fixed!!
