### ISSUE TITLE
Want to work on this repository

### ISSUE THREAD

**Issue by Raghu1124** [Ankit-Saha08/AIFF_Live_Updates#6]
@Ankit-Saha08 sir can you assign me, I will work on UI and add some extra functionality which will enhance the project.

**Comment by Ankit-Saha08** [comment]
@Raghu1124 I have assigned you on this task. Please go ahead.

**Comment by Ankit-Saha08** [comment]
@Raghu1124 Have you started working on the raised issue?

**Comment by Raghu1124** [comment]
> @Raghu1124 Have you started working on the raised issue?

yes sir working on it

**Comment by TandinDev** [comment]
Hello @Ankit-Saha08 is there any place, where I can give more input or work on?

**Comment by Ankit-Saha08** [comment]
@TandinDev please keep the conversation in issue #13 . I have replied there.

**Comment by Ankit-Saha08** [comment]
@Raghu1124 I did not receive any positive proposition about UI improvements from your end. So for now I'm closing this issue. If you wish to contribute again, please raise a new one!!
